"""
SmartFlow Database Models
=========================

Models for SmartFlow Indicator configuration and signal logs.
"""

from sqlalchemy import Column, Integer, String, Float, Boolean, DateTime, Text, ForeignKey, JSON
from sqlalchemy.orm import relationship
from datetime import datetime

from app.db.database import Base


class SmartFlowConfig(Base):
    """
    SmartFlow configuration per user

    Stores user's preferences for SmartFlow Indicator:
    - Enable/disable toggle
    - Webhook URLs to post signals to
    - Score thresholds
    - Update intervals
    """
    __tablename__ = "smartflow_config"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, unique=True)

    # Enable/disable
    enabled = Column(Boolean, default=False, nullable=False)

    # Webhook configuration
    webhook_urls = Column(JSON, nullable=False, default=list)  # List of webhook URLs to post signals to

    # Score thresholds
    buy_threshold = Column(Float, default=4.0, nullable=False)  # Score > this = buy signal
    sell_threshold = Column(Float, default=-4.0, nullable=False)  # Score < this = sell signal
    close_threshold = Column(Float, default=1.0, nullable=False)  # |Score| < this after extreme = close

    # Configuration
    score_window_minutes = Column(Integer, default=5, nullable=False)  # Flow window for scoring
    update_interval_seconds = Column(Integer, default=45, nullable=False)  # How often to compute scores

    # Enhanced toggles
    enable_vix_inverse = Column(Boolean, default=False, nullable=False)  # VIX/UVXY inverse sentiment
    enable_golden_sweeps = Column(Boolean, default=False, nullable=False)  # Golden sweep bonuses
    enable_leveraged_etfs = Column(Boolean, default=False, nullable=False)  # Use leveraged ETFs (SPXL/SPXU, etc.)
    vix_golden_threshold = Column(Float, default=100000.0, nullable=False)  # VIX golden sweep threshold
    min_premium = Column(Float, default=50000.0, nullable=False)  # Minimum flow premium to count

    # Confirmation filter toggles
    enable_price_confirmation = Column(Boolean, default=False, nullable=False)  # EMA filter
    enable_rsi_filter = Column(Boolean, default=False, nullable=False)  # RSI overbought/oversold filter
    enable_volume_filter = Column(Boolean, default=False, nullable=False)  # Volume spike requirement
    enable_time_filter = Column(Boolean, default=False, nullable=False)  # Time-of-day guard
    enable_fib_confluence = Column(Boolean, default=False, nullable=False)  # Fibonacci retracement bonus
    min_confidence_score = Column(Float, default=70.0, nullable=False)  # Minimum confidence % to execute

    # Confirmation filter parameters
    rsi_overbought = Column(Float, default=70.0, nullable=False)
    rsi_oversold = Column(Float, default=30.0, nullable=False)
    volume_spike_multiplier = Column(Float, default=1.5, nullable=False)
    time_filter_start_hour = Column(Integer, default=9, nullable=False)  # Market open hour (9am EST)
    time_filter_start_minute = Column(Integer, default=30, nullable=False)  # Market open minute (9:30am EST)
    time_filter_end_hour = Column(Integer, default=15, nullable=False)  # 3pm EST
    time_filter_end_minute = Column(Integer, default=0, nullable=False)  # End minute

    # AI Strategy Suite integration
    enable_ai_enhancement = Column(Boolean, default=False, nullable=False)  # Enable AI analysis
    ai_analysis_types = Column(JSON, default=['technical', 'patterns'])  # Analysis types to run
    block_on_ai_disagree = Column(Boolean, default=True, nullable=False)  # Block signals when AI disagrees
    check_market_trend = Column(Boolean, default=True, nullable=False)  # Check actual price trend
    # AI-Only Mode (24/7 trading)
    enable_ai_only_mode = Column(Boolean, default=False, nullable=False)  # Trade without flow data
    ai_only_scan_interval = Column(Integer, default=300, nullable=False)  # Seconds between scans
    ai_only_confidence_threshold = Column(Float, default=70.0, nullable=False)  # Min confidence to trade
    ai_only_instruments = Column(JSON, default=['MES', 'NQ', 'RTY', 'USDJPY', 'BTCUSD'])  # Instruments to trade

    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    # Relationships
    # user = relationship("User")  # One-way relationship, no back_populates needed
    signal_logs = relationship("SmartFlowSignalLog", back_populates="config", cascade="all, delete-orphan")


class SmartFlowSignalLog(Base):
    """
    Log of SmartFlow signals generated

    Stores history of all signals generated by SmartFlow for audit/analysis.
    """
    __tablename__ = "smartflow_signal_logs"

    id = Column(Integer, primary_key=True, index=True)
    config_id = Column(Integer, ForeignKey("smartflow_config.id"), nullable=False)

    # Signal details
    ticker = Column(String(10), nullable=False, index=True)  # MES, NQ, GC
    action = Column(String(10), nullable=False)  # buy, sell, close
    score = Column(Float, nullable=False)  # Sentiment score at signal time
    price = Column(Float, nullable=True)  # Price at signal time (if available)

    # Flow context
    bullish_flows = Column(Integer, default=0)  # Count of bullish flows in window
    bearish_flows = Column(Integer, default=0)  # Count of bearish flows in window
    total_premium = Column(Float, default=0.0)  # Total premium in window

    # AI-Only mode fields
    confidence = Column(Float, nullable=True)  # AI confidence % (for AI-Only signals)
    reason = Column(Text, nullable=True)  # AI reasoning or flow details

    # Webhook posting
    webhooks_posted = Column(JSON, nullable=False, default=list)  # List of webhook URLs posted to
    post_successful = Column(Boolean, default=False)  # All webhooks succeeded
    post_errors = Column(Text, nullable=True)  # Any errors encountered

    # Metadata
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)

    # Relationships
    config = relationship("SmartFlowConfig", back_populates="signal_logs")


class SmartFlowScoreHistory(Base):
    """
    Historical sentiment scores for charting

    Stores periodic sentiment score snapshots for dashboard charts.
    """
    __tablename__ = "smartflow_score_history"

    id = Column(Integer, primary_key=True, index=True)

    # Score details
    ticker = Column(String(10), nullable=False, index=True)  # SPY, QQQ, GLD
    score = Column(Float, nullable=False)  # Sentiment score
    bullish_flows = Column(Integer, default=0)
    bearish_flows = Column(Integer, default=0)
    total_premium = Column(Float, default=0.0)

    # Timestamp
    timestamp = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)

    # Note: This table can grow large, consider periodic cleanup (keep last 7 days)


# ============================================
# ML LEARNING TABLES
# ============================================

class SmartFlowPattern(Base):
    """
    Recognized flow patterns with historical performance.
    ML learns which patterns precede winning trades.
    """
    __tablename__ = "smartflow_patterns"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), nullable=False)
    description = Column(Text, nullable=True)

    # Pattern definition
    pattern_features = Column(JSON, nullable=False)
    pattern_type = Column(String(50), nullable=False)  # sweep, block, split, multi_leg

    # Historical performance
    total_occurrences = Column(Integer, default=0)
    win_count = Column(Integer, default=0)
    loss_count = Column(Integer, default=0)
    win_rate = Column(Float, default=0.0)
    avg_pnl = Column(Float, default=0.0)
    avg_pnl_winner = Column(Float, default=0.0)
    avg_pnl_loser = Column(Float, default=0.0)
    expectancy = Column(Float, default=0.0)
    profit_factor = Column(Float, default=0.0)

    # Confidence
    confidence_score = Column(Float, default=50.0)
    sample_size_weight = Column(Float, default=0.0)

    # Best conditions
    best_hour = Column(Integer, nullable=True)
    best_day = Column(Integer, nullable=True)
    best_regime = Column(String(20), nullable=True)

    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class SmartFlowSignalOutcome(Base):
    """
    Track P&L outcomes of signals for ML learning.
    This is the feedback loop that enables self-improvement.
    """
    __tablename__ = "smartflow_signal_outcomes"

    id = Column(Integer, primary_key=True, index=True)
    signal_log_id = Column(Integer, ForeignKey("smartflow_signal_logs.id"), nullable=False)

    # Trade outcome
    trade_executed = Column(Boolean, default=False, nullable=False)
    entry_price = Column(Float, nullable=True)
    exit_price = Column(Float, nullable=True)
    pnl = Column(Float, nullable=True)
    pnl_percent = Column(Float, nullable=True)
    is_winner = Column(Boolean, nullable=True)

    # Timing
    time_to_target = Column(Integer, nullable=True)
    time_in_trade = Column(Integer, nullable=True)
    max_favorable_excursion = Column(Float, nullable=True)
    max_adverse_excursion = Column(Float, nullable=True)

    # Market context at signal
    market_regime = Column(String(20), nullable=True)
    vix_level = Column(Float, nullable=True)
    spy_price = Column(Float, nullable=True)
    hour_of_day = Column(Integer, nullable=True)
    day_of_week = Column(Integer, nullable=True)

    # Flow context
    flow_pattern = Column(JSON, nullable=True)
    pattern_id = Column(Integer, ForeignKey("smartflow_patterns.id"), nullable=True)

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    # Relationships
    signal_log = relationship("SmartFlowSignalLog")
    pattern = relationship("SmartFlowPattern")


class SmartFlowModelState(Base):
    """
    ML model parameters and adaptive thresholds per ticker.
    Stores learned optimizations.
    """
    __tablename__ = "smartflow_model_state"

    id = Column(Integer, primary_key=True, index=True)
    ticker = Column(String(10), nullable=False, unique=True)

    # Adaptive thresholds (learned from outcomes)
    optimal_buy_threshold = Column(Float, default=4.0)
    optimal_sell_threshold = Column(Float, default=-4.0)
    optimal_close_threshold = Column(Float, default=1.0)

    # Confidence calibration
    fss_accuracy_by_range = Column(JSON, nullable=True)
    confidence_multiplier = Column(Float, default=1.0)

    # Time optimization
    hourly_win_rates = Column(JSON, nullable=True)
    best_trading_hours = Column(JSON, nullable=True)
    avoid_hours = Column(JSON, nullable=True)

    # Day optimization
    daily_win_rates = Column(JSON, nullable=True)
    best_trading_days = Column(JSON, nullable=True)

    # Recent performance
    recent_win_rate = Column(Float, default=0.5)
    recent_expectancy = Column(Float, default=0.0)
    recent_signals_count = Column(Integer, default=0)

    # Model versioning
    model_version = Column(Integer, default=1)
    last_trained_at = Column(DateTime, nullable=True)
    training_samples = Column(Integer, default=0)

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)


class SmartFlowMarketRegime(Base):
    """
    Track detected market regimes (trending, ranging, volatile).
    """
    __tablename__ = "smartflow_market_regimes"

    id = Column(Integer, primary_key=True, index=True)
    ticker = Column(String(10), nullable=False, index=True)

    # Regime classification
    regime = Column(String(20), nullable=False)
    regime_confidence = Column(Float, default=0.5)
    regime_strength = Column(Float, default=0.5)

    # Regime indicators
    atr_percentile = Column(Float, nullable=True)
    trend_strength = Column(Float, nullable=True)
    vix_level = Column(Float, nullable=True)
    volume_ratio = Column(Float, nullable=True)

    # Recommendations
    recommended_action = Column(String(20), nullable=True)
    size_multiplier = Column(Float, default=1.0)

    timestamp = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)


class SmartFlowMLMetrics(Base):
    """
    Daily ML performance metrics for tracking improvement over time.
    """
    __tablename__ = "smartflow_ml_metrics"

    id = Column(Integer, primary_key=True, index=True)
    ticker = Column(String(10), nullable=False, index=True)
    metric_date = Column(DateTime, nullable=False, index=True)

    # Daily performance
    signals_generated = Column(Integer, default=0)
    signals_executed = Column(Integer, default=0)
    winners = Column(Integer, default=0)
    losers = Column(Integer, default=0)
    win_rate = Column(Float, default=0.0)

    # P&L metrics
    gross_profit = Column(Float, default=0.0)
    gross_loss = Column(Float, default=0.0)
    net_pnl = Column(Float, default=0.0)
    profit_factor = Column(Float, default=0.0)
    expectancy = Column(Float, default=0.0)

    # ML-specific metrics
    model_confidence_avg = Column(Float, default=0.0)
    threshold_used = Column(Float, default=4.0)
    regime_accuracy = Column(Float, default=0.0)
    pattern_matches = Column(Integer, default=0)

    # Improvement tracking
    baseline_win_rate = Column(Float, default=0.5)
    improvement_vs_baseline = Column(Float, default=0.0)

    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)


class SmartFlowCorrelationSignal(Base):
    """
    Cross-ticker correlation events when multiple tickers align.
    """
    __tablename__ = "smartflow_correlation_signals"

    id = Column(Integer, primary_key=True, index=True)

    # Signal details
    signal_type = Column(String(20), nullable=False)
    direction = Column(String(10), nullable=False)
    confidence = Column(Float, nullable=False)

    # Participating tickers
    tickers_aligned = Column(JSON, nullable=False)
    alignment_scores = Column(JSON, nullable=False)
    total_tickers = Column(Integer, nullable=False)

    # Composite score
    composite_fss = Column(Float, nullable=False)
    conviction_level = Column(String(20), nullable=False)

    # Outcome tracking
    outcome_tracked = Column(Boolean, default=False)
    was_profitable = Column(Boolean, nullable=True)
    pnl = Column(Float, nullable=True)

    timestamp = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
